language: php

php:
- 5.6
- 5.5

sudo: false

before_script:
- composer self-update
- travis_retry composer install --prefer-dist --no-interaction
- composer global require phpunit/phpunit

script:
  - travis_retry phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)